### ISSUE TITLE
Zanotelli dataset: store neighb counts as altExps and cell neighbors as colPairs

### ISSUE THREAD

**Issue by ndamond** [BodenmillerGroup/imcdatasets#11]
As suggested by @nilseling (https://github.com/BodenmillerGroup/imcdatasets/pull/10#pullrequestreview-647127140), the ion counts of neighboring cells (i.e. `counts_neighb` and `exprs_neighb` in the `assay` slot) could be stored in the `altExps()` slot to avoid confusion between the counts of a cell and the counts of its neighbors.
In addition, cell neighbors information could be stored in the `colPairs` slot instead of being stored as a graph in the `metadata` slot.

**Comment by nilseling** [comment]
Ah, if you have already uploaded the data to ExperimentHub then no worries. It's only a minor detail and will not influence the usability of the dataset. Feel free to close the issue.

**Comment by ndamond** [comment]
Done with the new dataset versions (imcdatasets >= 1.5.3 / Bioconductor >= 3.16).

The dataset can be retrieved with: `sce <- Zanotelli_2020_Spheroids("sce")`.
Counts of neighboring cells are stored in the altExp() slot: `altExp(sce, "neighboring_cells")`.
Cell neighbors info is stored in the colPairs() slot: `colPair(sce, "neighborhood")`.
