### ISSUE TITLE
Make all datasets available as SpatialExperiment

### ISSUE THREAD

**Issue by ndamond** [BodenmillerGroup/imcdatasets#13]
In addition to `SingleCellExperiment`, make all datasets available as `SpatialExperiment` class objects.
https://bioconductor.org/packages/devel/bioc/html/SpatialExperiment.html

**Comment by nilseling** [comment]
I would not store the data twice but add an option (e.g. `retrieve_as = c("sce", "spe")`) to the load function. Internally, the `SpatialExperiment` object is constructed from the `SingleCellExperiment` object. What do you think?
