### ISSUE TITLE
listDatasets Doesn't Show Outcome Type(s) of Each Data Set

### ISSUE THREAD

**Issue by DarioS** [BodenmillerGroup/imcdatasets#24]
The table should display if outcome is categorical (e.g. responder, non-responder) and / or survival (e.g. recurrence-free survival days). Also, the number of patients per project is missing. Survival analysis needs a moderately high number to fit models stably.

**Comment by ndamond** [comment]
Hi DarioS,

The `listDatasets()` function only displays a short summary of available datasets, it is not meant to retrieve metadata that are not relevant across datasets.

Clinical metadata, when available, can be retrieved individually for each dataset via the `colData` slot of the `SingleCellExperiment` objects.

For instance:
```
sce <- imcdatasets::JacksonFischer_2020_BreastCancer("sce", full_dataset = TRUE)
meta <- colData(sce)
meta

# Number of patients
patient_ids <- unique(meta$patient_id)
length(patient_ids)

# Overall survival by patient
library(dplyr)
as_tibble(meta) %>%
  select(c(patient_id, patient_OS_months)) %>%
  distinct()
```

Best,
Nicolas

**Comment by DarioS** [comment]
Ah, O.K. but it will become more time-consuming to check each data set's metadata as the package grows with more additions. For example, Bioconductor package [MetaGxBreast](https://bioconductor.org/packages/release/data/experiment/html/MetaGxBreast.html) (39 data sets) has a function `loadBreastEsets` and a parameter `minNumberEvents`. Setting `minNumberEvents` to `1` (default value is `0`) or a greater integer makes it easy to find all survival time data sets programmatically quickly. Something similar would be a user experience improvement for imcdatasets.

**Comment by ndamond** [comment]
Thank you for the suggestion.
For now survival data are relevant for only two of the provided datasets and the primary goal of this package is to provide structured IMC data (i.e., images, masks and associated single-cell data).
Closing for now as there is no plan for implementing this in the near future.
